name: ristretto-tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main


jobs:
  ristretto-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Unit Tests
        run: go test -timeout=20m -race -covermode atomic -coverprofile=covprofile ./...
      - name: Save coverage profile
        uses: actions/upload-artifact@v4
        with:
          name: covprofile
          path: ./covprofile
